default: &default
  adapter: postgresql
  encoding: unicode
  username: mohammad_yaser
  password: 456
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: greeting_app_development
  username: postgres
  password: elpaso
test:
  <<: *default
  database: greeting_app_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>